### ISSUE TITLE
Getting error while running the script

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [skelsec/pypykatz#86] opened 2021-05-18 10:16 UTC
Hi!
I cloned the tool as mentioned, ran the setup.py, but now, when i execute the pypykatz.py script, It gives me this error.

`Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./pypykatz\__main__.py", line 150, in <module>
    main()
  File "./pypykatz\__main__.py", line 14, in main
    from pypykatz.utils.crypto.cmdhelper import CryptoCMDHelper
  File "./pypykatz\pypykatz.py", line 12, in <module>
    from pypykatz.commons.common import KatzSystemInfo
ModuleNotFoundError: No module named 'pypykatz.commons'; 'pypykatz' is not a package`

**Comment by Papotito123** [comment] 2021-05-19 04:29
Hello:
I have same error so I use lazagne.
I read that sometimes is due to pypypaktz folder multiplicity.Having a pypykatz folder with inside another pypykatz folder could lead to an error.

**Comment by Vedant-Bhalgama** [comment] 2021-05-19 04:47
Oh I see! I use LaZagne too, But i am just curious to try this one out! I will look if any solution is available! Thank You!

**Comment by skelsec** [comment] 2021-05-19 12:54
I can't reproduce this error. Clean ubuntu with python3.8 and 3.7 works from git master branch, and via pip as well.

**Comment by daniboomberger** [comment] 2021-08-01 20:42
Hey I didn't spent too much time looking into why it isn't working but I couldn't reproduce the error messages after installation if I used the following script in the `/usr/local/bin/pypykatz` that will be created after running `python3 setup.py install`.

But I could reproduce an error message when running the /pypykatz/pypykatz/pypykatz.py script directly as following `python3 /pypykatz/pypykatz/pypykatz.py`. As "Papotito123" stated in his comment the error could occur due to folder multiplicity.

Tested on:
- Fedora 34 (5.13.4-200.fc34.x86_64)
- Python 3.9.6

- Kali (5.10.0-kali7-amd64)
- Python 3.9.2

**Comment by skelsec** [comment] 2021-08-01 21:01
@daniboomberger but why would you want to run that script from the command line? that file doesn't have any command line interface functionality.  
All commandline functionality is in the `__main__.py` so you can use that via `python -m pypykatz` from the cloned `pypykatz` folder.
Can you please explain what you are trying to do?

**Comment by daniboomberger** [comment] 2021-08-01 21:06
@skelsec Oh lmao totally my bad. I misread the first problem that they try to run the pypykatz.py script directly that's why I tried to reproduce this. I don't get the error actually after installing, so I guess I can delete my comment.

**Comment by skelsec** [comment] 2021-08-02 20:26
Closing this issue since no other users had this and I can't reproduce

**Closed by skelsec** 2021-08-02 20:26 UTC
